name: Run Mockito Unit Tests for TechCorp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-techcorp:
    name: Test TechCorp with Mockito
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build TechCorp project
        run: mvn -f pom.xml clean test